#name, main, version and api are required
name: MyHeroMobs
main: Core.MyHeroMain
version: "0.1"
api: ["1.0.5"]
author: WindSkill
description: Plugin MyHero Mobs for Nukkit
depend: ["MobPlugin"]
softdepend: ["MyHeroItems"]
commands:
  MyHeroMobs:
    description: MyHero Mobs
    aliases: [mh,mhm]